# Generated by Django 6.0.3 on 2026-04-01 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='副標題')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='圖片')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='上架狀態')),
            ],
            options={
                'verbose_name': '輪播圖',
                'verbose_name_plural': '輪播圖',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='課程名稱')),
                ('instructor', models.CharField(max_length=100, verbose_name='講師')),
                ('description', models.TextField(verbose_name='課程介紹')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='課程封面')),
                ('capacity', models.IntegerField(verbose_name='名額限制')),
                ('start_time', models.DateTimeField(verbose_name='開課時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='開放報名')),
            ],
            options={
                'verbose_name': '課程',
                'verbose_name_plural': '課程',
            },
        ),
        migrations.CreateModel(
            name='DutyStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('role', models.CharField(max_length=50, verbose_name='職稱')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='聯絡方式')),
                ('is_on_duty', models.BooleanField(default=False, verbose_name='目前是否值班')),
            ],
            options={
                'verbose_name': '值班人員',
                'verbose_name_plural': '值班人員',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='服務名稱')),
                ('description', models.TextField(verbose_name='服務說明')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='圖片')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '三生共好服務',
                'verbose_name_plural': '三生共好服務',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='電話')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='報名時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inn_app.course', verbose_name='報名課程')),
            ],
            options={
                'verbose_name': '報名紀錄',
                'verbose_name_plural': '報名紀錄',
            },
        ),
    ]
