# Generated by Django 6.0.3 on 2026-04-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inn_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='結束時間'),
        ),
    ]
