# Generated by Django 6.0.3 on 2026-04-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inn_app', '0002_course_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='includes_lunch',
            field=models.BooleanField(default=False, verbose_name='是否提供午餐'),
        ),
        migrations.AddField(
            model_name='course',
            name='reg_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='報名截止時間'),
        ),
        migrations.AddField(
            model_name='course',
            name='reg_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='報名開始時間'),
        ),
    ]
