# Generated by Django 6.0.3 on 2026-04-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inn_app', '0004_alter_course_image_alter_registration_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_waitlisted',
            field=models.BooleanField(default=False, verbose_name='排入候補'),
        ),
    ]
