# Generated by Django 6.0.3 on 2026-04-01 02:30

import django.core.validators
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inn_app', '0005_registration_is_waitlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='checkin_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='掃碼憑證'),
        ),
        migrations.AddField(
            model_name='registration',
            name='headcount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='報名人數'),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_attended',
            field=models.BooleanField(default=False, verbose_name='已報到'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='課程介紹'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='服務說明'),
        ),
    ]
