# Generated by Django 6.0.3 on 2026-04-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inn_app', '0006_registration_checkin_token_registration_headcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='recommended_age',
            field=models.CharField(blank=True, help_text='例如：7歲以上、不限', max_length=50, verbose_name='建議年齡'),
        ),
        migrations.AddField(
            model_name='course',
            name='requires_computer',
            field=models.BooleanField(default=False, verbose_name='自備電腦'),
        ),
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他/不提供')], default='M', max_length=10, verbose_name='性別'),
        ),
    ]
