# Generated by Django 6.0.3 on 2026-04-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inn_app', '0007_course_recommended_age_course_requires_computer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigninTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='範本名稱')),
                ('file', models.FileField(help_text='請上傳含有 docxtpl 標籤的 .docx 檔案。', upload_to='templates/', verbose_name='Word 範本檔案')),
                ('is_default', models.BooleanField(default=False, verbose_name='預設選項')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '簽到表版型範本',
                'verbose_name_plural': '簽到表版型範本',
            },
        ),
    ]
