# Generated by Django 6.0.3 on 2026-04-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inn_app", "0008_signintemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="活動標題")),
                ("description", models.TextField(verbose_name="活動描述")),
                ("date", models.DateField(verbose_name="活動日期")),
            ],
            options={
                "verbose_name": "活動",
                "verbose_name_plural": "活動",
                "ordering": ["-date"],
            },
        ),
    ]
