# Generated by Django 6.0.3 on 2026-04-02 00:22

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inn_app", "0009_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperienceCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="課程名稱")),
                ("description", models.TextField(verbose_name="課程簡介")),
                (
                    "category",
                    models.CharField(
                        help_text="例如：不蒜花、機器人",
                        max_length=50,
                        verbose_name="分類",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="workshops/", verbose_name="課程圖示"),
                ),
            ],
            options={
                "verbose_name": "活動體驗課程說明",
                "verbose_name_plural": "活動體驗課程說明",
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="標題")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("local", "在地故事"),
                            ("usr", "USR 努力過程"),
                            ("achievement", "師生表現"),
                        ],
                        max_length=20,
                        verbose_name="分類",
                    ),
                ),
                ("content", tinymce.models.HTMLField(verbose_name="內容")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="stories/",
                        verbose_name="封面圖",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="發布時間"),
                ),
            ],
            options={
                "verbose_name": "故事牆",
                "verbose_name_plural": "故事牆",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TechProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="專案名稱")),
                (
                    "type",
                    models.CharField(
                        choices=[("aiot", "AIoT 應用"), ("ar_interact", "AR/互動導覽")],
                        max_length=20,
                        verbose_name="技術類型",
                    ),
                ),
                ("description", tinymce.models.HTMLField(verbose_name="技術細節說明")),
                ("image", models.ImageField(upload_to="tech/", verbose_name="示意圖")),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
            ],
            options={
                "verbose_name": "科技特色項目",
                "verbose_name_plural": "科技特色項目",
            },
        ),
        migrations.CreateModel(
            name="USRAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="成果標題")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("news", "新聞報導"),
                            ("video", "影片成果"),
                            ("display", "成果展示"),
                        ],
                        max_length=20,
                        verbose_name="類型",
                    ),
                ),
                ("summary", models.TextField(verbose_name="簡介")),
                (
                    "external_link",
                    models.URLField(
                        blank=True,
                        help_text="例如：影片網址或新聞連結",
                        null=True,
                        verbose_name="外部連結",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="achievements/",
                        verbose_name="代表圖",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
            ],
            options={
                "verbose_name": "USR成果",
                "verbose_name_plural": "USR成果",
                "ordering": ["-date"],
            },
        ),
    ]
