# Generated by Django 5.2.12 on 2026-04-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inn_app", "0010_experiencecourse_story_techproject_usrachievement"),
    ]

    operations = [
        migrations.AddField(
            model_name="carouselitem",
            name="show_subtitle",
            field=models.BooleanField(default=True, verbose_name="顯示副標題"),
        ),
        migrations.AddField(
            model_name="carouselitem",
            name="show_title",
            field=models.BooleanField(default=True, verbose_name="顯示標題"),
        ),
    ]
