# Generated by Django 5.2.12 on 2026-04-05 08:10

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inn_app", "0011_carouselitem_show_subtitle_carouselitem_show_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="區塊標題")),
                (
                    "intro_text",
                    tinymce.models.HTMLField(blank=True, verbose_name="前言/簡介"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tech_sections/",
                        verbose_name="側邊圖片",
                    ),
                ),
                (
                    "layout_type",
                    models.CharField(
                        choices=[
                            ("side_image", "左圖右卡片 (AIoT 樣式)"),
                            ("side_text", "左文右方塊 (AR 樣式)"),
                        ],
                        default="side_image",
                        max_length=20,
                        verbose_name="排版樣式",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
            ],
            options={
                "verbose_name": "科技專案區塊",
                "verbose_name_plural": "科技專案區塊",
                "ordering": ["order"],
            },
        ),
        migrations.AlterModelOptions(
            name="techproject",
            options={
                "ordering": ["order"],
                "verbose_name": "科技特色項目",
                "verbose_name_plural": "科技特色項目",
            },
        ),
        migrations.AddField(
            model_name="techproject",
            name="order",
            field=models.IntegerField(default=0, verbose_name="排序"),
        ),
        migrations.AlterField(
            model_name="techproject",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="tech/", verbose_name="示意圖"
            ),
        ),
        migrations.AlterField(
            model_name="techproject",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("aiot", "AIoT 應用"), ("ar_interact", "AR/互動導覽")],
                max_length=20,
                verbose_name="技術類型 (舊版)",
            ),
        ),
        migrations.AddField(
            model_name="techproject",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="inn_app.techsection",
                verbose_name="所屬區塊",
            ),
        ),
    ]
