# Generated by Django 5.2.12 on 2026-04-05 08:14

from django.db import migrations


def migrate_tech_data(apps, schema_editor):
    TechSection = apps.get_model('inn_app', 'TechSection')
    TechProject = apps.get_model('inn_app', 'TechProject')

    # Create AIoT Section
    s1, created = TechSection.objects.get_or_create(
        title='AIoT 應用：智慧轉型的願景',
        defaults={
            'intro_text': '透過感測器與雲端監控，我們協助水井村的農漁民轉型。不僅減少了人力成本，更透過精準數據分析，穩定了生產品質。',
            'layout_type': 'side_image',
            'order': 1
        }
    )
    
    # Create AR Section
    s2, created = TechSection.objects.get_or_create(
        title='AR/互動導覽',
        defaults={
            'intro_text': '''利用手機掃描水井牆上的 QR Code，即可召喚專屬 AR 導航小精靈，帶領您遊覽古道與光雕牆。
<div class="mt-4">
    <div class="d-flex align-items-center mb-3">
        <i class="fa-solid fa-check-circle text-success me-2"></i>
        <span>水井光導覽點位：目前已建置 5 個點位</span>
    </div>
    <div class="d-flex align-items-center mb-3">
        <i class="fa-solid fa-check-circle text-success me-2"></i>
        <span>即時語音說明：透過語音讀取在地歷史故事</span>
    </div>
    <div class="d-flex align-items-center">
        <i class="fa-solid fa-check-circle text-success me-2"></i>
        <span>互動解謎任務：適合親子共學，探索水井村三寶</span>
    </div>
</div>''',
            'layout_type': 'side_text',
            'order': 2
        }
    )

    # Link existing projects only if they don't have a section yet
    TechProject.objects.filter(type='aiot', section__isnull=True).update(section=s1)
    TechProject.objects.filter(type='ar_interact', section__isnull=True).update(section=s2)

class Migration(migrations.Migration):

    dependencies = [
        ("inn_app", "0012_techsection_alter_techproject_options_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_tech_data),
    ]
