# Generated by Django 5.2.12 on 2026-04-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inn_app", "0013_migrate_tech_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="聯絡我們", max_length=100, verbose_name="頁面標題"
                    ),
                ),
                (
                    "intro_text",
                    models.TextField(
                        default="有任何問題或是想要預約特別活動嗎？歡迎隨時與我們聯繫！我們會盡快回覆您。",
                        verbose_name="前言簡介",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="桃園市水井村風雲街 8 號",
                        max_length=200,
                        verbose_name="地址",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="(03) 1234-5678", max_length=50, verbose_name="電話"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="service@fengyuninn.com",
                        max_length=254,
                        verbose_name="電子郵件",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
            ],
            options={
                "verbose_name": "聯絡資訊設定",
                "verbose_name_plural": "聯絡資訊設定",
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("phone", models.CharField(max_length=50, verbose_name="電話")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("message", models.TextField(verbose_name="訊息內容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收件時間"),
                ),
            ],
            options={
                "verbose_name": "聯絡訊息收件夾",
                "verbose_name_plural": "聯絡訊息收件夾",
                "ordering": ["-created_at"],
            },
        ),
    ]
