# Generated by Django 5.2.13 on 2026-04-14 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inn_app', '0014_contactinfo_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='使用者名稱')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC 地址')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='瀏覽器/裝置')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登入時間')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登入者')),
            ],
            options={
                'verbose_name': '登入紀錄',
                'verbose_name_plural': '登入紀錄',
                'ordering': ['-login_time'],
            },
        ),
    ]
