# Generated by Django 5.2.13 on 2026-04-14 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inn_app', '0015_loginrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='map_iframe',
            field=models.TextField(blank=True, help_text='請貼上 Google Maps 分享的 iframe 語法', verbose_name='Google Map 嵌入語法'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=models.FileField(upload_to='carousel/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'mp4', 'webm', 'mov'])], verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(null=True, upload_to='courses/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'mp4', 'webm', 'mov'])], verbose_name='課程封面'),
        ),
        migrations.AlterField(
            model_name='experiencecourse',
            name='image',
            field=models.FileField(upload_to='workshops/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'mp4', 'webm', 'mov'])], verbose_name='課程圖示'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(null=True, upload_to='services/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'mp4', 'webm', 'mov'])], verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='stories/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'mp4', 'webm', 'mov'])], verbose_name='封面圖'),
        ),
        migrations.AlterField(
            model_name='techproject',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='tech/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'mp4', 'webm', 'mov'])], verbose_name='示意圖'),
        ),
        migrations.AlterField(
            model_name='techsection',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='tech_sections/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'mp4', 'webm', 'mov'])], verbose_name='側邊圖片'),
        ),
        migrations.AlterField(
            model_name='usrachievement',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='achievements/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'mp4', 'webm', 'mov'])], verbose_name='代表圖'),
        ),
    ]
