# Generated by Django 5.2.12 on 2026-04-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inn_app", "0016_contactinfo_map_iframe_alter_carouselitem_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="attended_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="報到時間"),
        ),
    ]
